server:
  port: 18080

#基本配置，文件上传，数据源，redis
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#      location: userFiles
  application:
    name: recruitment_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruitmenttest?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.124.2
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        #max-wait=1000
        min-idle: 0
  jpa:
    show-sql: true

#配置mybatis
mybatis:
#  configuration: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.scau.linyuanbin.recruitment.domain
#  配置深度延迟加载
#  configuration:
#    配置直接延迟加载，默认为false
#    lazy-loading-enabled: true
#    配置侵入式延迟加载，默认为true
#    aggressive-lazy-loading: false

#配置阿里云上oss访问资源
aliyun:
  file:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4FuY23ynLHffyzfTVoWh
    accessKeySecret: RaFFO8hNjk0IHuueleM0GozHgBALdW
    bucketName: marvellin
    folder: recruitment
    webUrl: https://marvellin.oss-cn-beijing.aliyuncs.com


#日志配置
#logging:
#  level: org.springframework.web=DEBUG
#  level: org.springframework.security=DEBUG